package com.example.gcontact.model.data

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a contact entity in the database.
 *
 * @param id Unique identifier for the contact, auto-generated by Room.
 * @param name The first name of the contact.
 * @param family The last name of the contact.
 * @param phoneNumber The phone number of the contact.
 * @param pictureUri The URI for the contact's profile picture.
 */
@Entity(tableName = "contact_table")
data class Contact(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0, // Primary key, auto-generated.
    val name: String, // First name of the contact.
    val family: String, // Last name of the contact.
    val phoneNumber: String, // Contact's phone number.
    val pictureUri: String // URI of the contact's profile picture.
)
